"""Unit tests for sessions.py's _first_user_message/_strip_injected_tags —
the fix for the Agents-nav picker showing a Claude session's auto-injected
wrapper text ("<local-command-caveat>Caveat: The messages below were
generated by the automated tool…") as its name instead of the real first
user message, found 2026-08-04.

Run: .venv/aw/bin/python -m pytest tests/test_first_user_message.py -q
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from tempfile import TemporaryDirectory

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from code_agent_clis_app.sessions import _first_user_message, _strip_injected_tags  # noqa: E402


def _write_jsonl(path: Path, records: list[dict]) -> None:
    path.write_text("\n".join(json.dumps(r) for r in records) + "\n")


def _user_record(text: str) -> dict:
    return {"type": "user", "message": {"role": "user", "content": text}}


def test_strip_injected_tags_removes_local_command_caveat():
    wrapped = (
        "<local-command-caveat>Caveat: The messages below were generated by "
        "the automated tool. Review carefully.</local-command-caveat>"
    )
    assert _strip_injected_tags(wrapped) == ""


def test_strip_injected_tags_leaves_real_text_untouched():
    assert _strip_injected_tags("fix the login bug") == "fix the login bug"


def test_strip_injected_tags_handles_truncated_tag():
    # A tag that got cut off before its closing counterpart (e.g. the
    # message was truncated somewhere upstream) — treat as pure noise.
    assert _strip_injected_tags("<local-command-caveat>Caveat: The mess") == ""


def test_first_user_message_skips_the_injected_caveat_and_finds_real_text():
    with TemporaryDirectory() as tmp:
        path = Path(tmp) / "session.jsonl"
        _write_jsonl(path, [
            {"sessionId": "abc"},
            _user_record(
                "<local-command-caveat>Caveat: The messages below were "
                "generated by the automated tool.</local-command-caveat>"
            ),
            _user_record("fix the login bug"),
        ])
        assert _first_user_message(str(path)) == "fix the login bug"


def test_first_user_message_returns_none_when_only_caveat_present():
    with TemporaryDirectory() as tmp:
        path = Path(tmp) / "session.jsonl"
        _write_jsonl(path, [
            _user_record(
                "<local-command-caveat>Caveat: The messages below were "
                "generated by the automated tool.</local-command-caveat>"
            ),
        ])
        assert _first_user_message(str(path)) is None


def test_first_user_message_truncates_long_text():
    with TemporaryDirectory() as tmp:
        path = Path(tmp) / "session.jsonl"
        long_text = "x" * 100
        _write_jsonl(path, [_user_record(long_text)])
        result = _first_user_message(str(path), max_len=60)
        assert result == "x" * 60 + "…"
